spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/learnJPQL
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '9099'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#    prometheus:
#      enabled: true
#    metrics:
#      enabled: true
#  global:
#    scrape_interval:     5s
#    evaluation_interval: 5s
#
#  scrape_configs:
#    - job_name: 'spring-boot'
#      metrics_path: '/actuator/prometheus'
#      static_configs:
#        - targets: ['localhost:9090']
#
#    - job_name: 'File-upload'
#      matrics_path: '/actuator/prometheus'
#      static_configs:
#        - targets: [ 'localhost:9099' ]